
services:
  backend:
    build:
      context: ./DashboardAPI
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - app-network
      
  frontend:
    build:
      context: ./DashboardClient
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge